### ISSUE TITLE
`Extractor:attibutes:usage` needs documentation and schema

### ISSUE THREAD

**Issue by PeterKraus** [marda-alliance/metadata_extractors_schema#19]
During the last office hours, we have settled on a first draft for the two variants of `usage`:

- `usage: "cli: executable {{ file_type }} {{ file_path }} {{ output_file }}"` for executing an `Extractor` from shell, with the obvious meanings of the parameters, returning the data as a file, and
- `usage: "python: project.module.function( {{ file_type }, {{ file_path }} )"` for executing an `Extractor` from python, returning the data as an in-memory object

This functionality is currently:
- undocumented: there is no explanation in the `Extractor` schema on how to compose these `usage` strings,
- unvalidated: the `Registry` machinery does not have a way to validate the `usage` string for syntax-correctness
- inconsistent: I would suggest renaming the `{{ file_path }}` pattern to `{{ input_file }}` for consistency with `{{ output_file }}`

**Comment by ml-evs** [comment]
Do we prefer a single string e.g., `cli: executable {{ file_type }} {{ file_path }} {{ output_file }}` or 

```
usage:
    - method: cli
      command: executable {{ file_type }} {{ file_path }} {{ output_file }}
    - method: python
      command: project.module.function( {{ file_type }, {{ file_path }} )
```

?

I can see benefits to both. The former would allow for structural validation via regexps directly (might be a slightly tasty regexp with conditionals...), the latter lets you filter usage more easily by method without needing to parse the string. It's not yet clear to me how to define the metaschema for {{ file_path }} etc in our current approach, perhaps we have to have a regexp that looks inside `{{ }}` and checks that the value is one of an enumerated list? Then we just bung all of that in the description of the field?
