### ISSUE TITLE
Allow filetype-specific usage instructions

### ISSUE THREAD

**Issue by ml-evs** [marda-alliance/metadata_extractors_schema#49]
e.g., `yadg` should be allowed to say, "here is my usage template for these formats, and here it is for these other formats":

e.g., 

```yaml
usage: 
    - method: python
      setup: yadg
      command: yadg.extractors.biologic_extract({{ input_type }}, {{ input_path }})
      filetypes: ["biologic-mpr", "biologic-mpt"]
    - method: python
      setup: yadg
      command: yadg.extractors.xrd_extract({{ input_type }}, {{ input_path }})
      filetypes: ["panalytical-xrdml"]
```

This feels a bit kludgey (and would need validation outside of LinkML to make sure that the types match the `support_filetypes`, and that all cases are covered), but is probably preferable to having to add multiple extractors in the registry?
